"""create users, reports, status history, risk predictions

Revision ID: 5ee70871431e
Revises: 
Create Date: 2026-09-10 18:25:23.360314

"""
from alembic import op
import sqlalchemy as sa
import geoalchemy2  # noqa: F401  (needed by autogenerated spatial columns)


# revision identifiers, used by Alembic.
revision = '5ee70871431e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # PostGIS must exist before any geography column can be created.
    op.execute('CREATE EXTENSION IF NOT EXISTS postgis')
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('risk_predictions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('location', geoalchemy2.types.Geography(geometry_type='POINT', srid=4326, dimension=2, spatial_index=False, from_text='ST_GeogFromText', name='geography', nullable=False), nullable=False),
    sa.Column('risk_score', sa.Float(), nullable=False),
    sa.Column('risk_level', sa.Enum('LOW', 'MEDIUM', 'HIGH', name='risk_level'), nullable=False),
    sa.Column('prediction_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('model_version', sa.String(length=50), nullable=False),
    sa.CheckConstraint('risk_score >= 0 AND risk_score <= 1', name='ck_risk_score_range'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('risk_predictions', schema=None) as batch_op:
        batch_op.create_index('idx_risk_predictions_location', ['location'], unique=False, postgresql_using='gist')
        batch_op.create_index(batch_op.f('ix_risk_predictions_prediction_date'), ['prediction_date'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('citizen', 'admin', name='user_role'), server_default='citizen', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('issue_type', sa.Enum('BLOCKED_DRAIN', 'WATERLOGGING', 'DRAIN_OVERFLOW', 'SEWAGE_OVERFLOW', 'DAMAGED_DRAIN', 'FLOODING', 'OTHER', name='issue_type'), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('severity', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='severity'), server_default='MEDIUM', nullable=False),
    sa.Column('status', sa.Enum('NEW', 'PENDING_VERIFICATION', 'VERIFIED', 'ASSIGNED', 'IN_PROGRESS', 'RESOLVED', 'REJECTED', name='report_status'), server_default='NEW', nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('location', geoalchemy2.types.Geography(geometry_type='POINT', srid=4326, dimension=2, spatial_index=False, from_text='ST_GeogFromText', name='geography', nullable=False), nullable=False),
    sa.Column('image_path', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('latitude >= -90 AND latitude <= 90', name='ck_reports_latitude_range'),
    sa.CheckConstraint('longitude >= -180 AND longitude <= 180', name='ck_reports_longitude_range'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.create_index('idx_reports_location', ['location'], unique=False, postgresql_using='gist')
        batch_op.create_index(batch_op.f('ix_reports_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_reports_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_reports_user_id'), ['user_id'], unique=False)

    op.create_table('report_status_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('report_id', sa.Integer(), nullable=False),
    sa.Column('old_status', sa.Enum('NEW', 'PENDING_VERIFICATION', 'VERIFIED', 'ASSIGNED', 'IN_PROGRESS', 'RESOLVED', 'REJECTED', name='report_status'), nullable=True),
    sa.Column('new_status', sa.Enum('NEW', 'PENDING_VERIFICATION', 'VERIFIED', 'ASSIGNED', 'IN_PROGRESS', 'RESOLVED', 'REJECTED', name='report_status'), nullable=False),
    sa.Column('changed_by', sa.Integer(), nullable=True),
    sa.Column('changed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['changed_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('report_status_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_report_status_history_changed_by'), ['changed_by'], unique=False)
        batch_op.create_index(batch_op.f('ix_report_status_history_report_id'), ['report_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('report_status_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_report_status_history_report_id'))
        batch_op.drop_index(batch_op.f('ix_report_status_history_changed_by'))

    op.drop_table('report_status_history')
    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reports_user_id'))
        batch_op.drop_index(batch_op.f('ix_reports_status'))
        batch_op.drop_index(batch_op.f('ix_reports_created_at'))
        batch_op.drop_index('idx_reports_location', postgresql_using='gist')

    op.drop_table('reports')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('risk_predictions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_risk_predictions_prediction_date'))
        batch_op.drop_index('idx_risk_predictions_location', postgresql_using='gist')

    op.drop_table('risk_predictions')
    # ### end Alembic commands ###
